### ISSUE TITLE
incorporate def.grp.file in make.prm.object

### ISSUE THREAD

**Issue by mdsumner** [Atlantis-Ecosystem-Model/shinyrAtlantis#4]
Currently this has to be also passed to sh.prm as an argument.

**Comment by shanearichards** [comment]
Can we avoid this? I would hope that the user would never see the files: paramdefns.csv and grpTemplates.csv and they remain hidden in the package. Can we use your trick you showed me (I forgot the function, system?) to access these files within the package, rather than using:

def.all.file <- paste(wd, "paramdefns.csv", sep = "")
def.grp.file <- paste(wd, "grpTemplates.csv", sep = "")
